### ISSUE TITLE
Addition doesn't respect TIS-100's numerical limits

### ISSUE THREAD

**Issue by embix** [barsae/TIS100#2]
see: [related Test cases as pull request](https://github.com/barsae/TIS100/pull/3)

possible fixes:
- fix Add operation (and probably Sub as well, not yet proven via test case)
- put constraints or overflow mapping in Number

**Comment by barsae** [comment]
Merged unit tests and added constraints in Number's constructor.

**Comment by embix** [comment]
wow, that was quick :-)
